version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

    
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database


  database:
    image: cassandra:4
    ports:
      - "9042:9042"
    volumes:
      - ./database:/var/lib/cassandra
